# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RomhackHispano
email: soywiz@gmail.com
description: RomhackHispano
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://romhackhispano.org" # the base hostname & protocol for your site
github_url: "http://github.com/romhackhispano/wiki.romhackhispano.org"
twitter_username: romhackhispano
facebook_username: romhackhispano
github_username:  romhackhispano
permalink: /:categories/:title

# Build settings
markdown: kramdown
